export const CLICK_UPDATE_VALUE = "CLICK_UPDATE_VALUE";
export const CLICK_CPF_CNPJ = "CLICK_CPF_CNPJ";
export const CLICK_IDENTIFICACAO = "CLICK_IDENTIFICACAO";
export const CLICK_CONTATO = "CLICK_CONTATO";
export const CLICK_ENDERECO = "CLICK_ENDERECO";
